/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_package;

/**
 *
 * @author jahna
 */
public class Options extends javax.swing.JFrame {

    /**
     * Creates new form Options
     */
    public Options() {
        initComponents();
        setBounds(50, 50,1338 , 754);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Summer");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 120, 120, 40);

        jList1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ladakh", "Kashmir", "Ooty", "Manali", "Darjeeling", "Rishikesh", "Munnar", "Goa", "Andaman" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 170, 180, 310);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Winter");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 120, 110, 40);

        jList2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rajasthan", "Goa", "Delhi", "Agra", "Kerala", "Lakshadweep", "Maharashtra", "Himachal " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(270, 170, 170, 310);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Monsoon");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 120, 140, 40);

        jList3.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cherrapunji", "Agra", "Delhi", "Rajasthan", "Lonavala", "Darjeeling", "Kodaikanal", "Kutch", "Kerala" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(490, 170, 170, 310);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trekking");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(700, 120, 130, 40);

        jList4.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Manali", "Munnar", "Rishikesh", "Kasol", "Shimla", "Darjeeling", "Mussoorie", "Kedarnath", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(690, 170, 170, 310);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Beaches");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(920, 120, 120, 40);

        jList5.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gujarat", "Goa", "Maharashtra", "Kerala", "Karnataka", "Tamil ", "Andhra ", "Bengal", "Odisha", "Andaman", "Lakshadweep", "Puducherry", "Daman", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(900, 170, 180, 310);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Most Common");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1120, 120, 200, 40);

        jList6.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Agra", "Varanasi", "Amritsar", "Jaisalmer", "New Delhi", "Mumbai", "Hyderabad", "Jaipur", "Goa", "Sikkim" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList6);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(1120, 170, 190, 310);

        jLabel7.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Please select any one place");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 560, 510, 50);

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(780, 560, 230, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/Choose.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 30, 1340, 750);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -30, 1340, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jList1.getSelectedValue()=="Ladakh"){
            LadakhSummer ladSum = new LadakhSummer();
            ladSum.show();
            dispose();
        }
        else if(jList1.getSelectedValue()=="Kashmir"){
            KashmirSummer kashSum = new KashmirSummer();
            kashSum.show();
            dispose();
        }
        else if(jList1.getSelectedValue()=="Ooty"){
            OotySummer ootySum = new OotySummer();
            ootySum.show();
            dispose();
        }
        else if(jList1.getSelectedValue()=="Manali"){
            Manali manalisum = new Manali();
            manalisum.show();
            dispose();
        }
        else if(jList1.getSelectedValue()=="Darjeeling"){
            DarjeelingSum darjSum = new DarjeelingSum();
            darjSum.show();
            dispose();
        }
        else if(jList1.getSelectedValue()=="Rishikesh"){
            RishikeshSumm rishiSum = new RishikeshSumm();
            rishiSum.show();
            dispose();
        }
        else if(jList1.getSelectedValue()=="Munnar"){
            Munnar munnSum = new Munnar();
            munnSum.show();;
            dispose();
        }
        else if(jList1.getSelectedValue()=="Goa"){
            GoaSumm goaSum = new GoaSumm();
            goaSum.show();
            dispose();
        }
        else if(jList1.getSelectedValue()=="Andaman"){
            AndamanSumm andnic = new AndamanSumm();
            andnic.show();
            dispose();
        }
        else if(jList2.getSelectedValue()=="Rajasthan"){
            RajasthanWin rajwin = new RajasthanWin();
            rajwin.show();
            dispose();
        }
        else if(jList2.getSelectedValue()=="Goa"){
            GoaWin goawin = new GoaWin();
            goawin.show();
            dispose();
        }
        else if(jList2.getSelectedValue()=="Delhi"){
            DelhiWin delwin = new DelhiWin();
            delwin.show();
            dispose();
        }
        else if(jList2.getSelectedValue()=="Agra"){
            AgraWin agra = new AgraWin();
            agra.show();
            dispose();
        }
        else if(jList2.getSelectedValue()=="Kerala"){
            KeralaWin kerala = new KeralaWin();
            kerala.show();
            dispose();
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
